diff --git a/makefile b/makefile
index 219a459..dd7c716 100644
--- a/makefile
+++ b/makefile
@@ -1,22 +1,21 @@
-# Process Server (for soft IOCs)
-# David H. Thompson 8/29/2003
-# Ralph Lange <ralph.lange@gmx.de> 02/29/2012
-# GNU Public License (GPLv3) applies - see www.gnu.org
+.if exists(Makefile)
+.include <Makefile>
+.else
 
-# Last resort rules if Makefile is not present
+AUTORECONF=autoreconf
 
-ifeq ($(wildcard Makefile),Makefile)
-include Makefile
-else
+all: autoreconf
 
-AUTORECONF=autoreconf
+autoreconf:
+    ${AUTORECONF} -si
+
+clean:
+    @echo Cleaning autotools debris
+    @rm -rf build-aux autom4te.cache
 
-all:	clean
-	$(AUTORECONF) -si
+distclean: clean
+    @rm -f configure aclocal.m4
 
-clean distclean maintainer-clean:
-	@echo Cleaning autotools debris
-	@rm -rf build-aux autom4te.cache
-	rm -f configure aclocal.m4 Makefile.in Makefile.Automake.in;
+maintainer-clean: distclean
 
-endif
+.endif
